

```{r}
#mapping to reference MI scSEQ data set (monocytes, macrophages, and dendritic-like cells 3, 7, 13, and 28 days after I/R) 

library(dplyr)
library(stringr)
library(viridis)
library(Seurat)
library(patchwork)
library(sctransform)
library(ggplot2)
library(harmony)
library(ggsci)
library(ggpubr)
library(pheatmap)
library(Matrix)
library(RColorBrewer)
library(scales)
library(data.table)
library(stats)
library(tibble)
library(tidyr)
```

```{r}
setwd("E:/arg1zsgr single cell")
```

```{r}
#unmapped object
myeloid <- readRDS("D:/arg1zsgr single cell/unmapped analysis/unmapped harmony.rds")
DimPlot(myeloid)
```

# Reference Mapping
```{r}
andrew_mouse <- readRDS("C:/Users/fkady/Desktop/andrew reclustered no ccrl2 121422/MonoTrack_Jan2023_UMAPmodel.rds")
DimPlot(andrew_mouse, reduction = "umap", label = TRUE)
```

```{r}
andrew_mouse <- FindNeighbors(andrew_mouse, reduction = "pca", dims = 1:40)
DimPlot(andrew_mouse, reduction = "umap", label = TRUE)
```

```{r}
andrew_mouse <- RunSPCA(andrew_mouse, assay = 'SCT', graph = 'SCT_snn')
DimPlot(andrew_mouse, reduction = "umap", label = TRUE)
```

```{r}
anchors <- FindTransferAnchors(
  reference = andrew_mouse,
  query = myeloid,
  normalization.method = "SCT",
  reference.reduction = "spca",
  reference.assay = "SCT",
  dims = 1:40
)
```

```{r}
myeloid <- MapQuery(
  anchorset = anchors,
  query = myeloid,
  reference = andrew_mouse,
  refdata = list(
    celltype = "Names"
  ),
  reference.reduction = "spca",
  reduction.model = "umap"
)
```

```{r}
DimPlot(myeloid, reduction = "ref.umap", group.by = "predicted.celltype", split.by = "condition")
```

```{r}
FeaturePlot(myeloid, features = "Arg1", reduction = "ref.umap", split.by = "condition", pt.size = 1)
```

```{r}
png(filename="./mapped arg1 vlnplt.png", width=10, height=10, units="cm", res=300)
VlnPlot(myeloid, features = "Arg1", group.by = "condition")
dev.off()
```

```{r}
#mapped object
saveRDS(myeloid, "./arg1zsgr_mapped.rds")
myeloid <- readRDS("./arg1zsgr_mapped.rds")
DimPlot(myeloid, reduction = "ref.umap", group.by = "predicted.celltype", split.by = "condition")
```

#plot of mapped data
```{r}
myeloid$predicted.celltype <- factor(x = myeloid$predicted.celltype, levels = c("Trem2", "Gdf15", "MHCII", "IFN", "Prolif", "Arg1", "cDC2", "Mono", "Ccl8", "Res"))

png(filename="./mapped data.png", width=25, height=20, units="cm", res=600)
DimPlot(myeloid, reduction = "ref.umap", label = FALSE, group.by = "predicted.celltype", pt.size = 3) + coord_fixed() +
  theme(legend.text=element_text(size=25))+
  scale_color_manual(values = c("#920000","#004949","#009292","#ff6db6","#490092","#006ddb","#24ff24","#db6d00","#b66dff","#6db6ff","#ffff6d","#ffb6db","#b6dbff","#924900"))
dev.off()

myeloid$condition <- factor(x = myeloid$condition, levels = c("ZNd2", "ZPd2", "ZNd30", "ZPd30"))

png(filename="./mapped data split.png", width=40, height=20, units="cm", res=600)
DimPlot(myeloid, reduction = "ref.umap", label = FALSE, group.by = "predicted.celltype", pt.size = 2, split.by = "condition") + coord_fixed() +
  theme(legend.text=element_text(size=25))+
  scale_color_manual(values = c("#920000","#004949","#009292","#ff6db6","#490092","#006ddb","#24ff24","#db6d00","#b66dff","#6db6ff","#ffff6d","#ffb6db","#b6dbff","#924900"))
dev.off()
```

#stacked barplot of cell 
```{r}
png(filename="./stacked barplot.png", width=40, height=20, units="cm", res=600)
ggplot(myeloid@meta.data, aes(x = condition, fill = predicted.celltype)) +
  geom_bar(position = "fill", width = 0.95) +
  xlab("Sample") +
  ylab("Proportion") +
  theme(legend.title = element_blank())+ coord_fixed(ratio=5)  +
  theme(legend.text=element_text(size=25)) +
  scale_fill_manual(values = c("#920000","#004949","#009292","#ff6db6","#490092","#006ddb","#24ff24","#db6d00","#b66dff","#6db6ff","#ffff6d","#ffb6db","#b6dbff","#924900"))+
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(legend.text=element_text(size=25))+ 
  theme(axis.text = element_text(size = 25))
dev.off()
```

#plot of mapping scores

```{r}
DefaultAssay(myeloid) <- "prediction.score.celltype"

png(filename="./mapping score Ccl8.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Ccl8", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

png(filename="./mapping score MHCII.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "MHCII", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

png(filename="./mapping score Trem2.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Trem2", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

png(filename="./mapping score Gdf15.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Gdf15", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

png(filename="./mapping score Res.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Res", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

png(filename="./mapping score Arg1.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Arg1", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

png(filename="./mapping score Prolif.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Prolif", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

png(filename="./mapping score Mono.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Mono", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

png(filename="./mapping score IFN.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "IFN", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

png(filename="./mapping score cDC2.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "cDC2", pt.size = 2, reduction = "ref.umap")  + coord_fixed() + 
  scale_color_gradientn(colors = c("lightgrey", "blue"), oob=scales::squish, limits=c(0,1.0))
dev.off()

```

```{r}
Idents(myeloid) <- "predicted.celltype"
myeloid.averageexpression <- AverageExpression(myeloid, features = c("Ccl8","MHCII","Trem2","Gdf15","Res","Arg1","Prolif","Mono","IFN","cDC2"),
                                               assays = "prediction.score.celltype")
myeloid.averageexpression <- as.matrix(myeloid.averageexpression)
mapping_scores <- myeloid.averageexpression[[1]]
list <- c("Ccl8","MHCII","Trem2","Gdf15","Res","Arg1","Prolif","Mono","IFN","cDC2")

png(filename="./mapping scores heatmap.png", width = 40, height = 20, units ="cm", res =300)
pheatmap(mapping_scores[,list], color=colorRampPalette(c("navy", "white", "orange"))(50), scale="none", cellheight = 30, cellwidth = 30, cexCol=0.5, cluster_rows=FALSE, fontsize_row=25, fontsize_col=25, cluster_cols = FALSE, legend = TRUE, fontsize = 20)
dev.off()
```

```{r}
Idents(myeloid) <- "predicted.celltype"
DefaultAssay(myeloid) <- 'SCT'
rna.markers <- FindAllMarkers(myeloid, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(rna.markers, file ="./DGE_GEX_predicted.celltype.csv", quote = FALSE)
```

#umap of andrew z scores on mapped data
```{r}
#Ccl8

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zCcl8 <- c("Ccl8","Gas6","Fabp5")
pops<-list(zCcl8)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$Ccl8_z<-z_scores[1,]

DotPlot(object = myeloid, features = "Ccl8_z")

png(filename="./andrew z score Ccl8.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Ccl8_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()

#MHCII

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zMHCII <- c("H2-Eb1", "H2-Aa", "Cd74", "H2-Ab1")
pops<-list(zMHCII)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$MHCII_z<-z_scores[1,]

DotPlot(object = myeloid, features = "MHCII_z")

png(filename="./andrew z score MHCII.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "MHCII_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()

#Trem2

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zTrem2 <- c("Trem2", "Fabp5", "Ctsd", "Gpnmb")
pops<-list(zTrem2)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$Trem2_z<-z_scores[1,]

DotPlot(object = myeloid, features = "Trem2_z")

png(filename="./andrew z score Trem2.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Trem2_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()

#Gdf15

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zGdf15 <- c("Gdf15", "Tnf", "Ccl4")
pops<-list(zGdf15)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$Gdf15_z<-z_scores[1,]

DotPlot(object = myeloid, features = "Gdf15_z")

png(filename="./andrew z score Gdf15.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Gdf15_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()

#Res

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zRes <- c("Lyve1", "Folr2", "Cd163", "Cbr2")
pops<-list(zRes)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$Res_z<-z_scores[1,]

DotPlot(object = myeloid, features = "Res_z")

png(filename="./andrew z score Res.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Res_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()

#Arg1

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zArg1 <- c("Arg1", "Fn1", "Cxcl1", "Tppp3")
pops<-list(zArg1)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$Arg1_z<-z_scores[1,]

DotPlot(object = myeloid, features = "Arg1_z")

png(filename="./andrew z score Arg1.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Arg1_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()

#Prolif

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zProlif <- c("Mki67", "Top2a", "Stmn1")
pops<-list(zProlif)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$Prolif_z<-z_scores[1,]

DotPlot(object = myeloid, features = "Prolif_z")

png(filename="./andrew z score Prolif.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Prolif_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()

#Mono

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zMono <- c("Plac8", "Ly6c2")
pops<-list(zMono)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$Mono_z<-z_scores[1,]

DotPlot(object = myeloid, features = "Mono_z")

png(filename="./andrew z score Mono.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "Mono_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()

#IFN

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zIFN <- c("Isg15", "Ifit3", "Irf7", "Cxcl10")
pops<-list(zIFN)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$IFN_z<-z_scores[1,]

DotPlot(object = myeloid, features = "IFN_z")

png(filename="./andrew z score IFN.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "IFN_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()

#cDC2

DefaultAssay(myeloid) <- "SCT"
expdata <- GetAssayData(myeloid)
zcDC2 <- c("Ifitm1", "Cd209a")
pops<-list(zcDC2)
#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
myeloid@meta.data$cDC2_z<-z_scores[1,]

DotPlot(object = myeloid, features = "cDC2_z")

png(filename="./andrew z score cDC2.png", width=20, height=20, units="cm", res=300)
FeaturePlot(myeloid, features = "cDC2_z", pt.size = 1.5, reduction = "ref.umap")  + coord_fixed() + scale_color_gradientn(colors=c("#0D0887FF", "#7E03A8FF", "#CC4678FF", "#F89441FF", "#F0F921FF"), oob=scales::squish, limits=c(0,1.5))
dev.off()
```

#dot plot of z scores across predicted populations
```{r}
#dot plot idents set to condition
Idents(myeloid) <- myeloid$predicted.celltype
list <- c("Trem2","Gdf15","MHCII","IFN","Prolif","Arg1","cDC2","Mono","Ccl8","Res")
myeloid@active.ident <- factor(x = myeloid@active.ident, levels = list)

png(filename = "./z score dot plot across populations.png", width = 25, height = 20, units = "cm", res = 600)
DotPlot(object = myeloid, features = c("Trem2_z", "Gdf15_z", "MHCII_z", "IFN_z", "Prolif_z", "Arg1_z", "cDC2_z", "Mono_z", "Ccl8_z", "Res_z"))+
  coord_fixed(ratio = 1)
dev.off()
```

#stacked barplot of cell zsgr+ only
```{r}
Idents(myeloid) <- "condition"
zsgrpos<- subset(myeloid, idents = c("ZPd2", "ZPd30"))

zsgrpos$predicted.celltype <- factor(x = zsgrpos$predicted.celltype, levels = c("Trem2", "Gdf15", "MHCII", "IFN", "Prolif", "Arg1", "cDC2", "Mono", "Ccl8", "Res"))

png(filename="./stacked barplot zsgr positive.png", width=40, height=20, units="cm", res=600)
ggplot(zsgrpos@meta.data, aes(x = condition, fill = predicted.celltype)) +
  geom_bar(position = "fill", width = 0.95) +
  xlab("Sample") +
  ylab("Proportion") +
  theme(legend.title = element_blank())+ coord_fixed(ratio=5)  +
  theme(legend.text=element_text(size=25)) +
  scale_fill_manual(values = c("#920000","#004949","#009292","#ff6db6","#490092","#006ddb","#24ff24","#db6d00","#b66dff","#6db6ff","#ffff6d","#ffb6db","#b6dbff","#924900"))+
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(legend.text=element_text(size=25))+ 
  theme(axis.text = element_text(size = 25))
dev.off()
```

#export for scanpy
```{r}
library(SeuratDisk)
```

```{r}
myeloid$condition <- as.character(myeloid$condition)
slot(myeloid$SCT@SCTModel.list[[1]], 'median_umi') = median(myeloid$SCT@SCTModel.list[[1]]@cell.attributes$umi)
```

```{r}
SaveH5Seurat(myeloid, filename = "./scanpy_mapped/myeloid.h5Seurat")
```

```{r}
Convert("./scanpy_mapped/myeloid.h5Seurat", dest = "h5ad")
```
